name: ke_le_me
description: "渴了么 - AI 智能喝水提醒"
publish_to: "none"
version: 2.5.1+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.4
  google_fonts: ^6.2.1
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_timezone: ^3.0.1
  dio: ^5.7.0
  geolocator: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
